import Head from "next/head";
import Contact from "./Contact";
import Portfolio from "./Portfolio";
import Hero from "./Hero";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Services from "./Services";
import Image from "next/image";
import Logo from "../public/wpLogo.svg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Willian Pires Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/wpLogo.svg" />
      </Head>
      <main className=" bg-white px-2 pt-5 md:px-20 lg:pd-40 dark:bg-gray-900">
        <nav className="flex justify-between bg-gray-800 py-3 px-5 mb-12 rounded-3xl md:mx-5 sm:mx-10 dark:bg-gray-800">
          <a href="">
            <Image src={Logo} className="text-sm" />
          </a>

          <ul className=" flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className=" cursor-pointer text-2xl text-white  dark:text-teal-500"
              />
            </li>
            <li>
              <a
                href="#contactForm"
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 ml-5 rounded-md"
              >
                Contact
              </a>
            </li>
          </ul>
        </nav>
        <Hero />
        <Services />
        <Portfolio />
        <Contact />
      </main>
    </div>
  );
}
